                    wget http://epg.51zmt.top:8000/tb1/CCTV/CCTV1.png      -O   tb1/CCTV/CCTV1.png
                    wget http://epg.51zmt.top:8000/tb1/CCTV/CCTV2.png      -O   tb1/CCTV/CCTV2.png
                    wget http://epg.51zmt.top:8000/tb1/CCTV/CCTV3.png      -O   tb1/CCTV/CCTV3.png
                    wget http://epg.51zmt.top:8000/tb1/CCTV/CCTV4.png      -O   tb1/CCTV/CCTV4.png
                    wget http://epg.51zmt.top:8000/tb1/CCTV/CCTV5.png      -O   tb1/CCTV/CCTV5.png
                    wget http://epg.51zmt.top:8000/tb1/CCTV/CCTV5+.png      -O   tb1/CCTV/CCTV5+.png
                    wget http://epg.51zmt.top:8000/tb1/CCTV/CCTV6.png      -O   tb1/CCTV/CCTV6.png
                    wget http://epg.51zmt.top:8000/tb1/CCTV/CCTV7.png      -O   tb1/CCTV/CCTV7.png
                    wget http://epg.51zmt.top:8000/tb1/CCTV/CCTV8.png      -O   tb1/CCTV/CCTV8.png
                    wget http://epg.51zmt.top:8000/tb1/CCTV/CCTV9.png      -O   tb1/CCTV/CCTV9.png
                    wget http://epg.51zmt.top:8000/tb1/CCTV/CCTV10.png      -O   tb1/CCTV/CCTV10.png
                    wget http://epg.51zmt.top:8000/tb1/CCTV/CCTV11.png      -O   tb1/CCTV/CCTV11.png
                    wget http://epg.51zmt.top:8000/tb1/CCTV/CCTV12.png      -O   tb1/CCTV/CCTV12.png
                    wget http://epg.51zmt.top:8000/tb1/CCTV/CCTV13.png      -O   tb1/CCTV/CCTV13.png
                    wget http://epg.51zmt.top:8000/tb1/CCTV/CCTV14.png      -O   tb1/CCTV/CCTV14.png
                    wget http://epg.51zmt.top:8000/tb1/CCTV/CCTV15.png      -O   tb1/CCTV/CCTV15.png
                    wget http://epg.51zmt.top:8000/tb1/CCTV/CCTV17.png      -O   tb1/CCTV/CCTV17.png
                    wget http://epg.51zmt.top:8000/tb1/CCTV/cgtn.png      -O   tb1/CCTV/cgtn.png
                    wget http://epg.51zmt.top:8000/tb1/CCTV/CCTV4EUO.png      -O   tb1/CCTV/CCTV4EUO.png
                    wget http://epg.51zmt.top:8000/tb1/CCTV/CCTV4AME.png      -O   tb1/CCTV/CCTV4AME.png
                    wget http://epg.51zmt.top:8000/tb1/CCTV/CCTV4k.png      -O   tb1/CCTV/CCTV4k.png
                    wget http://epg.51zmt.top:8000/tb1/CCTV/CCTV16.png      -O   tb1/CCTV/CCTV16.png
                    wget http://epg.51zmt.top:8000/tb1/ws/hunan.png      -O   tb1/ws/hunan.png
                    wget http://epg.51zmt.top:8000/tb1/ws/zhejiang.png      -O   tb1/ws/zhejiang.png
                    wget http://epg.51zmt.top:8000/tb1/ws/jiangsu.png      -O   tb1/ws/jiangsu.png
                    wget http://epg.51zmt.top:8000/tb1/ws/beijing.png      -O   tb1/ws/beijing.png
                    wget http://epg.51zmt.top:8000/tb1/ws/dongfang.png      -O   tb1/ws/dongfang.png
                    wget http://epg.51zmt.top:8000/tb1/ws/anhui.png      -O   tb1/ws/anhui.png
                    wget http://epg.51zmt.top:8000/tb1/ws/guangdong.png      -O   tb1/ws/guangdong.png
                    wget http://epg.51zmt.top:8000/tb1/ws/shenzhen.png      -O   tb1/ws/shenzhen.png
                    wget http://epg.51zmt.top:8000/tb1/ws/liaoning.png      -O   tb1/ws/liaoning.png
                    wget http://epg.51zmt.top:8000/tb1/ws/lvyou.png      -O   tb1/ws/lvyou.png
                    wget http://epg.51zmt.top:8000/tb1/ws/shandong.png      -O   tb1/ws/shandong.png
                    wget http://epg.51zmt.top:8000/tb1/ws/tianjin.png      -O   tb1/ws/tianjin.png
                    wget http://epg.51zmt.top:8000/tb1/ws/chongqing.png      -O   tb1/ws/chongqing.png
                    wget http://epg.51zmt.top:8000/tb1/ws/dongnan.png      -O   tb1/ws/dongnan.png
                    wget http://epg.51zmt.top:8000/tb1/ws/gansu.png      -O   tb1/ws/gansu.png
                    wget http://epg.51zmt.top:8000/tb1/ws/guangxi.png      -O   tb1/ws/guangxi.png
                    wget http://epg.51zmt.top:8000/tb1/ws/guizhou.png      -O   tb1/ws/guizhou.png
                    wget http://epg.51zmt.top:8000/tb1/ws/hebei.png      -O   tb1/ws/hebei.png
                    wget http://epg.51zmt.top:8000/tb1/ws/heilongjiang.png      -O   tb1/ws/heilongjiang.png
                    wget http://epg.51zmt.top:8000/tb1/ws/henan.png      -O   tb1/ws/henan.png
                    wget http://epg.51zmt.top:8000/tb1/ws/hubei.png      -O   tb1/ws/hubei.png
                    wget http://epg.51zmt.top:8000/tb1/ws/jiangxi.png      -O   tb1/ws/jiangxi.png
                    wget http://epg.51zmt.top:8000/tb1/ws/jilin.png      -O   tb1/ws/jilin.png
                    wget http://epg.51zmt.top:8000/tb1/ws/neimeng.png      -O   tb1/ws/neimeng.png
                    wget http://epg.51zmt.top:8000/tb1/ws/ningxia.png      -O   tb1/ws/ningxia.png
                    wget http://epg.51zmt.top:8000/tb1/ws/shanxi_.png      -O   tb1/ws/shanxi_.png
                    wget http://epg.51zmt.top:8000/tb1/ws/shanxi.png      -O   tb1/ws/shanxi.png
                    wget http://epg.51zmt.top:8000/tb1/ws/sichuan.png      -O   tb1/ws/sichuan.png
                    wget http://epg.51zmt.top:8000/tb1/ws/xinjiang.png      -O   tb1/ws/xinjiang.png
                    wget http://epg.51zmt.top:8000/tb1/ws/yunnan.png      -O   tb1/ws/yunnan.png
                    wget http://epg.51zmt.top:8000/tb1/ws/qinghai.png      -O   tb1/ws/qinghai.png
                    wget http://epg.51zmt.top:8000/tb1/ws/nanfang.png      -O   tb1/ws/nanfang.png
                    wget http://epg.51zmt.top:8000/tb1/ws/bingtuan.png      -O   tb1/ws/bingtuan.png
                    wget http://epg.51zmt.top:8000/tb1/ws/YANBIAN1.png      -O   tb1/ws/YANBIAN1.png
                    wget http://epg.51zmt.top:8000/tb1/ws/huanghe.png      -O   tb1/ws/huanghe.png
                    wget http://epg.51zmt.top:8000/tb1/ws/xiamen.png      -O   tb1/ws/xiamen.png
                    wget http://epg.51zmt.top:8000/tb1/qt/jinyingkatong.png      -O   tb1/qt/jinyingkatong.png
                    wget http://epg.51zmt.top:8000/tb1/ws/kangba.png      -O   tb1/ws/kangba.png
                    wget http://epg.51zmt.top:8000/tb1/ws/xizang.png      -O   tb1/ws/xizang.png
                    wget http://epg.51zmt.top:8000/tb1/ws/sansha.png      -O   tb1/ws/sansha.png
                    wget http://epg.51zmt.top:8000/tb1/qt/中国教育1台.png      -O   tb1/qt/中国教育1台.png
                    wget http://epg.51zmt.top:8000/tb1/qt/中国教育2台.png      -O   tb1/qt/中国教育2台.png
                    wget http://epg.51zmt.top:8000/tb1/qt/中国教育3台.png      -O   tb1/qt/中国教育3台.png
                    wget http://epg.51zmt.top:8000/tb1/CCTV/CCTV3D.png      -O   tb1/CCTV/CCTV3D.png
                    wget http://epg.51zmt.top:8000/tb1/qt/IPTVEFEL.png      -O   tb1/qt/IPTVEFEL.png
                    wget http://epg.51zmt.top:8000/tb1/qt/dianjingtiantang.png      -O   tb1/qt/dianjingtiantang.png
                    wget http://epg.51zmt.top:8000/tb1/qt/IPTV5+.png      -O   tb1/qt/IPTV5+.png
                    wget http://epg.51zmt.top:8000/tb1/qt/IPTV6+.png      -O   tb1/qt/IPTV6+.png
                    wget http://epg.51zmt.top:8000/tb1/qt/IPTV经典电影.png      -O   tb1/qt/IPTV经典电影.png
                    wget http://epg.51zmt.top:8000/tb1/qt/IPTV热播剧场.png      -O   tb1/qt/IPTV热播剧场.png
                    wget http://epg.51zmt.top:8000/tb1/qt/IPTV少儿动画.png      -O   tb1/qt/IPTV少儿动画.png
                    wget http://epg.51zmt.top:8000/tb1/qt/IPTV魅力时尚.png      -O   tb1/qt/IPTV魅力时尚.png
                    wget http://epg.51zmt.top:8000/tb1/CCTV/CCTVfengyunzuqiu.png      -O   tb1/CCTV/CCTVfengyunzuqiu.png
                    wget http://epg.51zmt.top:8000/tb1/qt/QSKX.jpg      -O   tb1/qt/QSKX.jpg
                    wget http://epg.51zmt.top:8000/tb1/qt/CHC3.jpg      -O   tb1/qt/CHC3.jpg
                    wget http://epg.51zmt.top:8000/tb1/qt/QSDW.jpg      -O   tb1/qt/QSDW.jpg
                    wget http://epg.51zmt.top:8000/tb1/qt/QSJL.jpg      -O   tb1/qt/QSJL.jpg
                    wget http://epg.51zmt.top:8000/tb1/qt/CHC1.jpg      -O   tb1/qt/CHC1.jpg
                    wget http://epg.51zmt.top:8000/tb1/qt/CHC2.jpg      -O   tb1/qt/CHC2.jpg
                    wget http://epg.51zmt.top:8000/tb1/qt/CCTVPAYFEE20.jpg      -O   tb1/qt/CCTVPAYFEE20.jpg
                    wget http://epg.51zmt.top:8000/tb1/CCTV/CCTVfengyunyinyue.png      -O   tb1/CCTV/CCTVfengyunyinyue.png
                    wget http://epg.51zmt.top:8000/tb1/CCTV/CCTVdiyijuchang.png      -O   tb1/CCTV/CCTVdiyijuchang.png
                    wget http://epg.51zmt.top:8000/tb1/CCTV/CCTBfengyun.png      -O   tb1/CCTV/CCTBfengyun.png
                    wget http://epg.51zmt.top:8000/tb1/CCTV/CCTVshijiedili.png      -O   tb1/CCTV/CCTVshijiedili.png
                    wget http://epg.51zmt.top:8000/tb1/qt/CCTVPAYFEE7.jpg      -O   tb1/qt/CCTVPAYFEE7.jpg
                    wget http://epg.51zmt.top:8000/tb1/qt/CCTVPAYFEE8.jpg      -O   tb1/qt/CCTVPAYFEE8.jpg
                    wget http://epg.51zmt.top:8000/tb1/CCTV/CCTVnvxing.png      -O   tb1/CCTV/CCTVnvxing.png
                    wget http://epg.51zmt.top:8000/tb1/CCTV/CCTVyule.png      -O   tb1/CCTV/CCTVyule.png
                    wget http://epg.51zmt.top:8000/tb1/CCTV/CCTVxiqu.png      -O   tb1/CCTV/CCTVxiqu.png
                    wget http://epg.51zmt.top:8000/tb1/qt/CCTVPAYFEE12.jpg      -O   tb1/qt/CCTVPAYFEE12.jpg
                    wget http://epg.51zmt.top:8000/tb1/qt/CCTVPAYFEE13.jpg      -O   tb1/qt/CCTVPAYFEE13.jpg
                    wget http://epg.51zmt.top:8000/tb1/CCTV/CCTVwenhuajingpin.png      -O   tb1/CCTV/CCTVwenhuajingpin.png
                    wget http://epg.51zmt.top:8000/tb1/qt/caiminzaixian.png      -O   tb1/qt/caiminzaixian.png
                    wget http://epg.51zmt.top:8000/tb1/qt/CCTVPAYFEE17.jpg      -O   tb1/qt/CCTVPAYFEE17.jpg
                    wget http://epg.51zmt.top:8000/tb1/qt/CCTVPAYFEE22.jpg      -O   tb1/qt/CCTVPAYFEE22.jpg
                    wget http://epg.51zmt.top:8000/tb1/qt/CCTVPAYFEE24.jpg      -O   tb1/qt/CCTVPAYFEE24.jpg
                    wget http://epg.51zmt.top:8000/tb1/qt/CCTVPAYFEE25.jpg      -O   tb1/qt/CCTVPAYFEE25.jpg
                    wget http://epg.51zmt.top:8000/tb1/qt/PHOTOGRAPHY-CHANNEL.jpg      -O   tb1/qt/PHOTOGRAPHY-CHANNEL.jpg
                    wget http://epg.51zmt.top:8000/tb1/qt/TIANYUANWEIQI.jpg      -O   tb1/qt/TIANYUANWEIQI.jpg
                    wget http://epg.51zmt.top:8000/tb1/qt/CCTVPAYFEE29.jpg      -O   tb1/qt/CCTVPAYFEE29.jpg
                    wget http://epg.51zmt.top:8000/tb1/qt/CCTVPAYFEE33.jpg      -O   tb1/qt/CCTVPAYFEE33.jpg
                    wget http://epg.51zmt.top:8000/tb1/CCTV/CCTVzhengquan.png      -O   tb1/CCTV/CCTVzhengquan.png
                    wget http://epg.51zmt.top:8000/tb1/CCTV/CCTVtaiqiu.png      -O   tb1/CCTV/CCTVtaiqiu.png
                    wget http://epg.51zmt.top:8000/tb1/qt/DOCUMENTARY-CHANNEL.jpg      -O   tb1/qt/DOCUMENTARY-CHANNEL.jpg
                    wget http://epg.51zmt.top:8000/tb1/qt/WUSHUSHIJIE.jpg      -O   tb1/qt/WUSHUSHIJIE.jpg
                    wget http://epg.51zmt.top:8000/tb1/CCTV/CCTVfaxianzhilv.png      -O   tb1/CCTV/CCTVfaxianzhilv.png
                    wget http://epg.51zmt.top:8000/tb1/qt/HUANQIUQIGUAN.jpg      -O   tb1/qt/HUANQIUQIGUAN.jpg
                    wget http://epg.51zmt.top:8000/tb1/qt/SHUOWENJIEZI.jpg      -O   tb1/qt/SHUOWENJIEZI.jpg
                    wget http://epg.51zmt.top:8000/tb1/qt/WENWUBAOKU.jpg      -O   tb1/qt/WENWUBAOKU.jpg
                    wget http://epg.51zmt.top:8000/tb1/CCTV/CCTVxinke.png      -O   tb1/CCTV/CCTVxinke.png
                    wget http://epg.51zmt.top:8000/tb1/qt/YOUERJIAOYU.jpg      -O   tb1/qt/YOUERJIAOYU.jpg
                    wget http://epg.51zmt.top:8000/tb1/CCTV/CCTVlaogushi.png      -O   tb1/CCTV/CCTVlaogushi.png
                    wget http://epg.51zmt.top:8000/tb1/qt/KUAILECHUIDIAO.jpg      -O   tb1/qt/KUAILECHUIDIAO.jpg
                    wget http://epg.51zmt.top:8000/tb1/qt/CCTVPAYFEE37.jpg      -O   tb1/qt/CCTVPAYFEE37.jpg
                    wget http://epg.51zmt.top:8000/tb1/qt/DOXTV.jpg      -O   tb1/qt/DOXTV.jpg
                    wget http://epg.51zmt.top:8000/tb1/qt/XFBY.jpg      -O   tb1/qt/XFBY.jpg
                    wget http://epg.51zmt.top:8000/tb1/qt/BAMC1.jpg      -O   tb1/qt/BAMC1.jpg
                    wget http://epg.51zmt.top:8000/tb1/qt/BAMC3.jpg      -O   tb1/qt/BAMC3.jpg
                    wget http://epg.51zmt.top:8000/tb1/qt/BAMC4.jpg      -O   tb1/qt/BAMC4.jpg
                    wget http://epg.51zmt.top:8000/tb1/qt/BAMC5.jpg      -O   tb1/qt/BAMC5.jpg
                    wget http://epg.51zmt.top:8000/tb1/qt/BAMC6.jpg      -O   tb1/qt/BAMC6.jpg
                    wget http://epg.51zmt.top:8000/tb1/qt/BAMC7.jpg      -O   tb1/qt/BAMC7.jpg
                    wget http://epg.51zmt.top:8000/tb1/qt/BAMC8.jpg      -O   tb1/qt/BAMC8.jpg
                    wget http://epg.51zmt.top:8000/tb1/qt/BAMC10.jpg      -O   tb1/qt/BAMC10.jpg
                    wget http://epg.51zmt.top:8000/tb1/qt/BAMC14.jpg      -O   tb1/qt/BAMC14.jpg
                    wget http://epg.51zmt.top:8000/tb1/qt/BAMC17.jpg      -O   tb1/qt/BAMC17.jpg
                    wget http://epg.51zmt.top:8000/tb1/qt/BAMC18.jpg      -O   tb1/qt/BAMC18.jpg
                    wget http://epg.51zmt.top:8000/tb1/qt/BAMC19.jpg      -O   tb1/qt/BAMC19.jpg
                    wget http://epg.51zmt.top:8000/tb1/qt/财富天下.png      -O   tb1/qt/财富天下.png
                    wget http://epg.51zmt.top:8000/tb1/qt/CHTV.jpg      -O   tb1/qt/CHTV.jpg
                    wget http://epg.51zmt.top:8000/tb1/qt/HSJPJC.jpg      -O   tb1/qt/HSJPJC.jpg
                    wget http://epg.51zmt.top:8000/tb1/qt/HSSEDM.jpg      -O   tb1/qt/HSSEDM.jpg
                    wget http://epg.51zmt.top:8000/tb1/qt/OMYY.jpg      -O   tb1/qt/OMYY.jpg
                    wget http://epg.51zmt.top:8000/tb1/qt/中国教育4台.png      -O   tb1/qt/中国教育4台.png
                    wget http://epg.51zmt.top:8000/tb1/qt/kaku.png      -O   tb1/qt/kaku.png
                    wget http://epg.51zmt.top:8000/tb1/ws/beijingjishi.png      -O   tb1/ws/beijingjishi.png
                    wget http://epg.51zmt.top:8000/tb1/sheng/BTV文艺.png      -O   tb1/sheng/BTV文艺.png
                    wget http://epg.51zmt.top:8000/tb1/sheng/BTV科教.png      -O   tb1/sheng/BTV科教.png
                    wget http://epg.51zmt.top:8000/tb1/sheng/BTV影视.png      -O   tb1/sheng/BTV影视.png
                    wget http://epg.51zmt.top:8000/tb1/sheng/BTV财经.png      -O   tb1/sheng/BTV财经.png
                    wget http://epg.51zmt.top:8000/tb1/sheng/BTV生活.png      -O   tb1/sheng/BTV生活.png
                    wget http://epg.51zmt.top:8000/tb1/sheng/BTV青年.png      -O   tb1/sheng/BTV青年.png
                    wget http://epg.51zmt.top:8000/tb1/sheng/BTV新闻.png      -O   tb1/sheng/BTV新闻.png
                    wget http://epg.51zmt.top:8000/tb1/qt/xuandong.png      -O   tb1/qt/xuandong.png
                    wget http://epg.51zmt.top:8000/tb1/qt/DOX_YAQU.png      -O   tb1/qt/DOX_YAQU.png
                    wget http://epg.51zmt.top:8000/tb1/qt/qicaixiju.png      -O   tb1/qt/qicaixiju.png
                    wget http://epg.51zmt.top:8000/tb1/qt/xinshijue.png      -O   tb1/qt/xinshijue.png
                    wget http://epg.51zmt.top:8000/tb1/qt/jinbaotiyu.jpg      -O   tb1/qt/jinbaotiyu.jpg
                    wget http://epg.51zmt.top:8000/tb1/qt/dox_yinglun.png      -O   tb1/qt/dox_yinglun.png
                    wget http://epg.51zmt.top:8000/tb1/qt/dox_juchang.png      -O   tb1/qt/dox_juchang.png
                    wget http://epg.51zmt.top:8000/tb1/qt/jisuqiche.png      -O   tb1/qt/jisuqiche.png
                    wget http://epg.51zmt.top:8000/tb1/qt/quanjishi.png      -O   tb1/qt/quanjishi.png
                    wget http://epg.51zmt.top:8000/tb1/qt/huanxiao.png      -O   tb1/qt/huanxiao.png
                    wget http://epg.51zmt.top:8000/tb1/qt/xingfucai.png      -O   tb1/qt/xingfucai.png
                    wget http://epg.51zmt.top:8000/tb1/qt/shenghuoshishang.png      -O   tb1/qt/shenghuoshishang.png
                    wget http://epg.51zmt.top:8000/tb1/qt/youxifengyun.png      -O   tb1/qt/youxifengyun.png
                    wget http://epg.51zmt.top:8000/tb1/qt/shangshixinwen.png      -O   tb1/qt/shangshixinwen.png
                    wget http://epg.51zmt.top:8000/tb1/qt/diyicaijing.png      -O   tb1/qt/diyicaijing.png
                    wget http://epg.51zmt.top:8000/tb1/qt/shanghaidongfangyingshi.png      -O   tb1/qt/shanghaidongfangyingshi.png
                    wget http://epg.51zmt.top:8000/tb1/qt/wuxingtiyu.png      -O   tb1/qt/wuxingtiyu.png
                    wget http://epg.51zmt.top:8000/tb1/ws/shanghaijishi.png      -O   tb1/ws/shanghaijishi.png
                    wget http://epg.51zmt.top:8000/tb1/qt/shanghaidushi.jpg      -O   tb1/qt/shanghaidushi.jpg
                    wget http://epg.51zmt.top:8000/tb1/qt/shanghaiwaiyu.png      -O   tb1/qt/shanghaiwaiyu.png
                    wget http://epg.51zmt.top:8000/tb1/CCTV/zgjt.png      -O   tb1/CCTV/zgjt.png
                    wget http://epg.51zmt.top:8000/tb1/qt/meilizuqiu.png      -O   tb1/qt/meilizuqiu.png
                    wget http://epg.51zmt.top:8000/tb1/sheng/sctv2.png      -O   tb1/sheng/sctv2.png
                    wget http://epg.51zmt.top:8000/tb1/sheng/sctv3.png      -O   tb1/sheng/sctv3.png
                    wget http://epg.51zmt.top:8000/tb1/sheng/sctv4.png      -O   tb1/sheng/sctv4.png
                    wget http://epg.51zmt.top:8000/tb1/sheng/sctv5.png      -O   tb1/sheng/sctv5.png
                    wget http://epg.51zmt.top:8000/tb1/sheng/sctv7.png      -O   tb1/sheng/sctv7.png
                    wget http://epg.51zmt.top:8000/tb1/qt/emeidianying.png      -O   tb1/qt/emeidianying.png
                    wget http://epg.51zmt.top:8000/tb1/sheng/sctv9.png      -O   tb1/sheng/sctv9.png
                    wget http://epg.51zmt.top:8000/tb1/sheng/sctv8.png      -O   tb1/sheng/sctv8.png
                    wget http://epg.51zmt.top:8000/tb1/sheng/cdtv1.png      -O   tb1/sheng/cdtv1.png
                    wget http://epg.51zmt.top:8000/tb1/sheng/cdtv2.png      -O   tb1/sheng/cdtv2.png
                    wget http://epg.51zmt.top:8000/tb1/sheng/cdtv3.png      -O   tb1/sheng/cdtv3.png
                    wget http://epg.51zmt.top:8000/tb1/sheng/cdtv4.png      -O   tb1/sheng/cdtv4.png
                    wget http://epg.51zmt.top:8000/tb1/sheng/cdtv5.png      -O   tb1/sheng/cdtv5.png
                    wget http://epg.51zmt.top:8000/tb1/sheng/cdtv6.png      -O   tb1/sheng/cdtv6.png
                    wget http://epg.51zmt.top:8000/tb1/sheng/aishang4k.png      -O   tb1/sheng/aishang4k.png
                    wget http://epg.51zmt.top:8000/tb1/qt/sd_qilu.png      -O   tb1/qt/sd_qilu.png
                    wget http://epg.51zmt.top:8000/tb1/qt/sd_tiyu.png      -O   tb1/qt/sd_tiyu.png
                    wget http://epg.51zmt.top:8000/tb1/qt/sd_nongke.png      -O   tb1/qt/sd_nongke.png
                    wget http://epg.51zmt.top:8000/tb1/qt/sd_gonggong.png      -O   tb1/qt/sd_gonggong.png
                    wget http://epg.51zmt.top:8000/tb1/qt/sd_shaoer.png      -O   tb1/qt/sd_shaoer.png
                    wget http://epg.51zmt.top:8000/tb1/qt/sd_yingshi.png      -O   tb1/qt/sd_yingshi.png
                    wget http://epg.51zmt.top:8000/tb1/qt/sd_zongyi.png      -O   tb1/qt/sd_zongyi.png
                    wget http://epg.51zmt.top:8000/tb1/qt/sd_shenghuo.png      -O   tb1/qt/sd_shenghuo.png
                    wget http://epg.51zmt.top:8000/tb1/qt/sd_huanyudianying.jpg      -O   tb1/qt/sd_huanyudianying.jpg
                    wget http://epg.51zmt.top:8000/tb1/qt/gtv_youxi.png      -O   tb1/qt/gtv_youxi.png
                    wget http://epg.51zmt.top:8000/tb1/qt/wangluoqipai.png      -O   tb1/qt/wangluoqipai.png
                    wget http://epg.51zmt.top:8000/tb1/qt/xindongman.png      -O   tb1/qt/xindongman.png
                    wget http://epg.51zmt.top:8000/tb1/qt/LNTV2.jpg      -O   tb1/qt/LNTV2.jpg
                    wget http://epg.51zmt.top:8000/tb1/qt/LNTV3.jpg      -O   tb1/qt/LNTV3.jpg
                    wget http://epg.51zmt.top:8000/tb1/qt/LNTV5.jpg      -O   tb1/qt/LNTV5.jpg
                    wget http://epg.51zmt.top:8000/tb1/qt/LNTV6.jpg      -O   tb1/qt/LNTV6.jpg
                    wget http://epg.51zmt.top:8000/tb1/qt/LNTV7.jpg      -O   tb1/qt/LNTV7.jpg
                    wget http://epg.51zmt.top:8000/tb1/qt/LNTV8.jpg      -O   tb1/qt/LNTV8.jpg
                    wget http://epg.51zmt.top:8000/tb1/qt/LNTV-SPORT.jpg      -O   tb1/qt/LNTV-SPORT.jpg
                    wget http://epg.51zmt.top:8000/tb1/qt/LNTV-FINANCE.jpg      -O   tb1/qt/LNTV-FINANCE.jpg
                    wget http://epg.51zmt.top:8000/tb1/qt/LNSY1.jpg      -O   tb1/qt/LNSY1.jpg
                    wget http://epg.51zmt.top:8000/tb1/qt/HUBEI2.png      -O   tb1/qt/HUBEI2.png
                    wget http://epg.51zmt.top:8000/tb1/qt/HUBEI3.png      -O   tb1/qt/HUBEI3.png
                    wget http://epg.51zmt.top:8000/tb1/qt/HUBEI4.png      -O   tb1/qt/HUBEI4.png
                    wget http://epg.51zmt.top:8000/tb1/qt/HUBEI5.png      -O   tb1/qt/HUBEI5.png
                    wget http://epg.51zmt.top:8000/tb1/qt/HUBEI7.png      -O   tb1/qt/HUBEI7.png
                    wget http://epg.51zmt.top:8000/tb1/qt/HUBEI8.png      -O   tb1/qt/HUBEI8.png
                    wget http://epg.51zmt.top:8000/tb1/qt/HBLS.png      -O   tb1/qt/HBLS.png
                    wget http://epg.51zmt.top:8000/tb1/qt/WHTV1.png      -O   tb1/qt/WHTV1.png
                    wget http://epg.51zmt.top:8000/tb1/qt/WHTV2.png      -O   tb1/qt/WHTV2.png
                    wget http://epg.51zmt.top:8000/tb1/qt/WHTV3.png      -O   tb1/qt/WHTV3.png
                    wget http://epg.51zmt.top:8000/tb1/qt/WHTV4.png      -O   tb1/qt/WHTV4.png
                    wget http://epg.51zmt.top:8000/tb1/qt/WHTV5.png      -O   tb1/qt/WHTV5.png
                    wget http://epg.51zmt.top:8000/tb1/qt/WHTV6.png      -O   tb1/qt/WHTV6.png
                    wget http://epg.51zmt.top:8000/tb1/qt/WHTV7.png      -O   tb1/qt/WHTV7.png
                    wget http://epg.51zmt.top:8000/tb1/qt/WETV.png      -O   tb1/qt/WETV.png
                    wget http://epg.51zmt.top:8000/tb1/qt/liangzhuang.png      -O   tb1/qt/liangzhuang.png
                    wget http://epg.51zmt.top:8000/tb1/qt/youman.png      -O   tb1/qt/youman.png
                    wget http://epg.51zmt.top:8000/tb1/qt/dv_shenghuo.png      -O   tb1/qt/dv_shenghuo.png
                    wget http://epg.51zmt.top:8000/tb1/qt/jiajiakt.png      -O   tb1/qt/jiajiakt.png
                    wget http://epg.51zmt.top:8000/tb1/gt/zhujiang.png      -O   tb1/gt/zhujiang.png
                    wget http://epg.51zmt.top:8000/tb1/ws/jinyingjishi.png      -O   tb1/ws/jinyingjishi.png
                    wget http://epg.51zmt.top:8000/tb1/gt/TVB翡翠台.png      -O   tb1/gt/TVB翡翠台.png
                    wget http://epg.51zmt.top:8000/tb1/gt/TVB明珠台.png      -O   tb1/gt/TVB明珠台.png
                    wget http://epg.51zmt.top:8000/tb1/gt/TVBclassic.png      -O   tb1/gt/TVBclassic.png
                    wget http://epg.51zmt.top:8000/tb1/gt/wxxw.png      -O   tb1/gt/wxxw.png
                    wget http://epg.51zmt.top:8000/tb1/gt/tvbfinanceinformationchannel.png      -O   tb1/gt/tvbfinanceinformationchannel.png
                    wget http://epg.51zmt.top:8000/tb1/gt/fenghuangzhongwen.png      -O   tb1/gt/fenghuangzhongwen.png
                    wget http://epg.51zmt.top:8000/tb1/gt/fenghuangzixun.png      -O   tb1/gt/fenghuangzixun.png
                    wget http://epg.51zmt.top:8000/tb1/gt/fenghuangxianggang.png      -O   tb1/gt/fenghuangxianggang.png
                    wget http://epg.51zmt.top:8000/tb1/gt/yangguangweishi.png      -O   tb1/gt/yangguangweishi.png
                    wget http://epg.51zmt.top:8000/tb1/gt/meiyamovie.png      -O   tb1/gt/meiyamovie.png
                    wget http://epg.51zmt.top:8000/tb1/gt/viutv.png      -O   tb1/gt/viutv.png
                    wget http://epg.51zmt.top:8000/tb1/gt/hks.png      -O   tb1/gt/hks.png
                    wget http://epg.51zmt.top:8000/tb1/gt/TVBJ2.png      -O   tb1/gt/TVBJ2.png
                    wget http://epg.51zmt.top:8000/tb1/gt/hkguojicaijing.png      -O   tb1/gt/hkguojicaijing.png
                    wget http://epg.51zmt.top:8000/tb1/gt/hongkongkai.png      -O   tb1/gt/hongkongkai.png
                    wget http://epg.51zmt.top:8000/tb1/gt/youxiancaijingzixun.png      -O   tb1/gt/youxiancaijingzixun.png
                    wget http://epg.51zmt.top:8000/tb1/gt/youxianxinwen.png      -O   tb1/gt/youxianxinwen.png
                    wget http://epg.51zmt.top:8000/tb1/gt/hongkong603.png      -O   tb1/gt/hongkong603.png
                    wget http://epg.51zmt.top:8000/tb1/gt/TVB星河.png      -O   tb1/gt/TVB星河.png
                    wget http://epg.51zmt.top:8000/tb1/gt/starmov.png      -O   tb1/gt/starmov.png
                    wget http://epg.51zmt.top:8000/tb1/gt/EbcAsiaNews.png      -O   tb1/gt/EbcAsiaNews.png
                    wget http://epg.51zmt.top:8000/tb1/gt/EbcAsiaWeishi.png      -O   tb1/gt/EbcAsiaWeishi.png
                    wget http://epg.51zmt.top:8000/tb1/gt/PublicTV2.png      -O   tb1/gt/PublicTV2.png
                    wget http://epg.51zmt.top:8000/tb1/gt/GoodTV2.png      -O   tb1/gt/GoodTV2.png
                    wget http://epg.51zmt.top:8000/tb1/gt/NEXTTVZonghe.png      -O   tb1/gt/NEXTTVZonghe.png
                    wget http://epg.51zmt.top:8000/tb1/gt/NEXTTVMovie.png      -O   tb1/gt/NEXTTVMovie.png
                    wget http://epg.51zmt.top:8000/tb1/gt/BabyTV.png      -O   tb1/gt/BabyTV.png
                    wget http://epg.51zmt.top:8000/tb1/gt/PublicTV3HD.png      -O   tb1/gt/PublicTV3HD.png
                    wget http://epg.51zmt.top:8000/tb1/gt/FTV.png      -O   tb1/gt/FTV.png
                    wget http://epg.51zmt.top:8000/tb1/gt/台视.png      -O   tb1/gt/台视.png
                    wget http://epg.51zmt.top:8000/tb1/gt/daai.png      -O   tb1/gt/daai.png
                    wget http://epg.51zmt.top:8000/tb1/gt/中视.png      -O   tb1/gt/中视.png
                    wget http://epg.51zmt.top:8000/tb1/gt/BeautifulLife.png      -O   tb1/gt/BeautifulLife.png
                    wget http://epg.51zmt.top:8000/tb1/gt/CTS.png      -O   tb1/gt/CTS.png
                    wget http://epg.51zmt.top:8000/tb1/gt/PublicTV.png      -O   tb1/gt/PublicTV.png
                    wget http://epg.51zmt.top:8000/tb1/gt/GoodTV.png      -O   tb1/gt/GoodTV.png
                    wget http://epg.51zmt.top:8000/tb1/gt/yuanzhumin.png      -O   tb1/gt/yuanzhumin.png
                    wget http://epg.51zmt.top:8000/tb1/gt/HakkaTV.png      -O   tb1/gt/HakkaTV.png
                    wget http://epg.51zmt.top:8000/tb1/gt/MOMOkids.png      -O   tb1/gt/MOMOkids.png
                    wget http://epg.51zmt.top:8000/tb1/gt/EBCYoYoTV.png      -O   tb1/gt/EBCYoYoTV.png
                    wget http://epg.51zmt.top:8000/tb1/gt/VideolandOnTV.png      -O   tb1/gt/VideolandOnTV.png
                    wget http://epg.51zmt.top:8000/tb1/gt/GTVOneHD.png      -O   tb1/gt/GTVOneHD.png
                    wget http://epg.51zmt.top:8000/tb1/gt/GTVVarietyHD.png      -O   tb1/gt/GTVVarietyHD.png
                    wget http://epg.51zmt.top:8000/tb1/gt/SETTaiwan.png      -O   tb1/gt/SETTaiwan.png
                    wget http://epg.51zmt.top:8000/tb1/gt/SETCity.png      -O   tb1/gt/SETCity.png
                    wget http://epg.51zmt.top:8000/tb1/gt/卫视中文.png      -O   tb1/gt/卫视中文.png
                    wget http://epg.51zmt.top:8000/tb1/gt/EBCVariety.png      -O   tb1/gt/EBCVariety.png
                    wget http://epg.51zmt.top:8000/tb1/gt/EBCSuper.png      -O   tb1/gt/EBCSuper.png
                    wget http://epg.51zmt.top:8000/tb1/gt/CtiVariety.png      -O   tb1/gt/CtiVariety.png
                    wget http://epg.51zmt.top:8000/tb1/gt/东风卫视.png      -O   tb1/gt/东风卫视.png
                    wget http://epg.51zmt.top:8000/tb1/gt/年代MUCH.png      -O   tb1/gt/年代MUCH.png
                    wget http://epg.51zmt.top:8000/tb1/gt/CtiEntertainment.png      -O   tb1/gt/CtiEntertainment.png
                    wget http://epg.51zmt.top:8000/tb1/gt/EBCDrama.png      -O   tb1/gt/EBCDrama.png
                    wget http://epg.51zmt.top:8000/tb1/gt/GTVDramaHD.png      -O   tb1/gt/GTVDramaHD.png
                    wget http://epg.51zmt.top:8000/tb1/gt/TVBS欢乐.png      -O   tb1/gt/TVBS欢乐.png
                    wget http://epg.51zmt.top:8000/tb1/gt/VideolandDrama.png      -O   tb1/gt/VideolandDrama.png
                    wget http://epg.51zmt.top:8000/tb1/gt/TOPTVHD.png      -O   tb1/gt/TOPTVHD.png
                    wget http://epg.51zmt.top:8000/tb1/gt/JETVariety.png      -O   tb1/gt/JETVariety.png
                    wget http://epg.51zmt.top:8000/tb1/gt/NextTVNews.png      -O   tb1/gt/NextTVNews.png
                    wget http://epg.51zmt.top:8000/tb1/gt/年代ERANewsHD.png      -O   tb1/gt/年代ERANewsHD.png
                    wget http://epg.51zmt.top:8000/tb1/gt/EBCNews.png      -O   tb1/gt/EBCNews.png
                    wget http://epg.51zmt.top:8000/tb1/gt/FTVNews.png      -O   tb1/gt/FTVNews.png
                    wget http://epg.51zmt.top:8000/tb1/gt/SETNews.png      -O   tb1/gt/SETNews.png
                    wget http://epg.51zmt.top:8000/tb1/gt/TVBS新闻.png      -O   tb1/gt/TVBS新闻.png
                    wget http://epg.51zmt.top:8000/tb1/gt/TVBS.png      -O   tb1/gt/TVBS.png
                    wget http://epg.51zmt.top:8000/tb1/gt/EBCFinancialNews.png      -O   tb1/gt/EBCFinancialNews.png
                    wget http://epg.51zmt.top:8000/tb1/gt/UniqueNews.png      -O   tb1/gt/UniqueNews.png
                    wget http://epg.51zmt.top:8000/tb1/gt/StarChineseMovies.png      -O   tb1/gt/StarChineseMovies.png
                    wget http://epg.51zmt.top:8000/tb1/gt/EBCMovies.png      -O   tb1/gt/EBCMovies.png
                    wget http://epg.51zmt.top:8000/tb1/gt/VideolandMovies.png      -O   tb1/gt/VideolandMovies.png
                    wget http://epg.51zmt.top:8000/tb1/gt/LSTIME.png      -O   tb1/gt/LSTIME.png
                    wget http://epg.51zmt.top:8000/tb1/gt/EBCWesternMovies.png      -O   tb1/gt/EBCWesternMovies.png
                    wget http://epg.51zmt.top:8000/tb1/gt/HMC.png      -O   tb1/gt/HMC.png
                    wget http://epg.51zmt.top:8000/tb1/gt/VideolandMaxTV.png      -O   tb1/gt/VideolandMaxTV.png
                    wget http://epg.51zmt.top:8000/tb1/gt/VideolandSportsHD.png      -O   tb1/gt/VideolandSportsHD.png
                    wget http://epg.51zmt.top:8000/tb1/gt/VideolandJapanese.png      -O   tb1/gt/VideolandJapanese.png
                    wget http://epg.51zmt.top:8000/tb1/gt/GoldSunTV.png      -O   tb1/gt/GoldSunTV.png
                    wget http://epg.51zmt.top:8000/tb1/gt/靖天综合.png      -O   tb1/gt/靖天综合.png
                    wget http://epg.51zmt.top:8000/tb1/gt/靖天资讯.png      -O   tb1/gt/靖天资讯.png
                    wget http://epg.51zmt.top:8000/tb1/gt/SinJiTVHD.png      -O   tb1/gt/SinJiTVHD.png
                    wget http://epg.51zmt.top:8000/tb1/gt/靖洋戏剧.png      -O   tb1/gt/靖洋戏剧.png
                    wget http://epg.51zmt.top:8000/tb1/gt/ChampionTV1.png      -O   tb1/gt/ChampionTV1.png
                    wget http://epg.51zmt.top:8000/tb1/gt/TACT.png      -O   tb1/gt/TACT.png
                    wget http://epg.51zmt.top:8000/tb1/gt/CostarTV.png      -O   tb1/gt/CostarTV.png
                    wget http://epg.51zmt.top:8000/tb1/gt/UniqueUSTVHDUSTVHD.png      -O   tb1/gt/UniqueUSTVHDUSTVHD.png
                    wget http://epg.51zmt.top:8000/tb1/gt/SETInews.png      -O   tb1/gt/SETInews.png
                    wget http://epg.51zmt.top:8000/tb1/gt/EFTV.png      -O   tb1/gt/EFTV.png
                    wget http://epg.51zmt.top:8000/tb1/gt/SBN.png      -O   tb1/gt/SBN.png
                    wget http://epg.51zmt.top:8000/tb1/gt/ChengSinTV.png      -O   tb1/gt/ChengSinTV.png
                    wget http://epg.51zmt.top:8000/tb1/gt/mtvlivehd.png      -O   tb1/gt/mtvlivehd.png
                    wget http://epg.51zmt.top:8000/tb1/gt/靖天映画.png      -O   tb1/gt/靖天映画.png
                    wget http://epg.51zmt.top:8000/tb1/gt/海豚综合.png      -O   tb1/gt/海豚综合.png
                    wget http://epg.51zmt.top:8000/tb1/gt/PiliPuppet.png      -O   tb1/gt/PiliPuppet.png
                    wget http://epg.51zmt.top:8000/tb1/gt/CosmosBuddhistMissionaryTV.png      -O   tb1/gt/CosmosBuddhistMissionaryTV.png
                    wget http://epg.51zmt.top:8000/tb1/gt/SinDaTV.png      -O   tb1/gt/SinDaTV.png
                    wget http://epg.51zmt.top:8000/tb1/gt/HwaZanTV.png      -O   tb1/gt/HwaZanTV.png
                    wget http://epg.51zmt.top:8000/tb1/gt/ZChannel.png      -O   tb1/gt/ZChannel.png
                    wget http://epg.51zmt.top:8000/tb1/gt/BudddhaCompassionTV.png      -O   tb1/gt/BudddhaCompassionTV.png
                    wget http://epg.51zmt.top:8000/tb1/gt/shengming.png      -O   tb1/gt/shengming.png
                    wget http://epg.51zmt.top:8000/tb1/gt/TienLiangTVHD.png      -O   tb1/gt/TienLiangTVHD.png
                    wget http://epg.51zmt.top:8000/tb1/gt/ChengTeTV.png      -O   tb1/gt/ChengTeTV.png
                    wget http://epg.51zmt.top:8000/tb1/gt/TOPTV2.png      -O   tb1/gt/TOPTV2.png
                    wget http://epg.51zmt.top:8000/tb1/gt/ChampionTV2.png      -O   tb1/gt/ChampionTV2.png
                    wget http://epg.51zmt.top:8000/tb1/gt/GTVEntertainment.png      -O   tb1/gt/GTVEntertainment.png
                    wget http://epg.51zmt.top:8000/tb1/gt/DaliTV.png      -O   tb1/gt/DaliTV.png
                    wget http://epg.51zmt.top:8000/tb1/gt/gstv.png      -O   tb1/gt/gstv.png
                    wget http://epg.51zmt.top:8000/tb1/gt/daai2.png      -O   tb1/gt/daai2.png
                    wget http://epg.51zmt.top:8000/tb1/gt/台视新闻.png      -O   tb1/gt/台视新闻.png
                    wget http://epg.51zmt.top:8000/tb1/gt/台视财经.png      -O   tb1/gt/台视财经.png
                    wget http://epg.51zmt.top:8000/tb1/gt/台视综合.png      -O   tb1/gt/台视综合.png
                    wget http://epg.51zmt.top:8000/tb1/gt/靖天欢乐.png      -O   tb1/gt/靖天欢乐.png
                    wget http://epg.51zmt.top:8000/tb1/gt/靖天育乐.png      -O   tb1/gt/靖天育乐.png
                    wget http://epg.51zmt.top:8000/tb1/gt/靖天日本.png      -O   tb1/gt/靖天日本.png
                    wget http://epg.51zmt.top:8000/tb1/gt/FoodNetwork.png      -O   tb1/gt/FoodNetwork.png
                    wget http://epg.51zmt.top:8000/tb1/gt/HGTV.png      -O   tb1/gt/HGTV.png
                    wget http://epg.51zmt.top:8000/tb1/gt/travelchannel.png      -O   tb1/gt/travelchannel.png
                    wget http://epg.51zmt.top:8000/tb1/gt/afc.png      -O   tb1/gt/afc.png
                    wget http://epg.51zmt.top:8000/tb1/gt/GlobalNews.png      -O   tb1/gt/GlobalNews.png
                    wget http://epg.51zmt.top:8000/tb1/gt/asiatravel.png      -O   tb1/gt/asiatravel.png
                    wget http://epg.51zmt.top:8000/tb1/gt/sports_net_2.png      -O   tb1/gt/sports_net_2.png
                    wget http://epg.51zmt.top:8000/tb1/gt/sport_tennis.png      -O   tb1/gt/sport_tennis.png
                    wget http://epg.51zmt.top:8000/tb1/gt/sport_unlimited.png      -O   tb1/gt/sport_unlimited.png
                    wget http://epg.51zmt.top:8000/tb1/gt/sports-golfch.png      -O   tb1/gt/sports-golfch.png
                    wget http://epg.51zmt.top:8000/tb1/gt/sport-golfplus.png      -O   tb1/gt/sport-golfplus.png
                    wget http://epg.51zmt.top:8000/tb1/gt/sport-trendsport.png      -O   tb1/gt/sport-trendsport.png
                    wget http://epg.51zmt.top:8000/tb1/gt/sport-sports_net.png      -O   tb1/gt/sport-sports_net.png
                    wget http://epg.51zmt.top:8000/tb1/gt/sport_unlimited2.png      -O   tb1/gt/sport_unlimited2.png
                    wget http://epg.51zmt.top:8000/tb1/gt/davinci.png      -O   tb1/gt/davinci.png
                    wget http://epg.51zmt.top:8000/tb1/gt/靖洋卡通.png      -O   tb1/gt/靖洋卡通.png
                    wget http://epg.51zmt.top:8000/tb1/gt/靖天卡通.png      -O   tb1/gt/靖天卡通.png
                    wget http://epg.51zmt.top:8000/tb1/gt/SETZonghe.png      -O   tb1/gt/SETZonghe.png
                    wget http://epg.51zmt.top:8000/tb1/gt/龙华偶像.png      -O   tb1/gt/龙华偶像.png
                    wget http://epg.51zmt.top:8000/tb1/gt/龙华戏剧.png      -O   tb1/gt/龙华戏剧.png
                    wget http://epg.51zmt.top:8000/tb1/gt/龙华电影.png      -O   tb1/gt/龙华电影.png
                    wget http://epg.51zmt.top:8000/tb1/gt/龙华经典.png      -O   tb1/gt/龙华经典.png
                    wget http://epg.51zmt.top:8000/tb1/gt/龙华影剧.png      -O   tb1/gt/龙华影剧.png
                    wget http://epg.51zmt.top:8000/tb1/gt/龙华洋片.png      -O   tb1/gt/龙华洋片.png
                    wget http://epg.51zmt.top:8000/tb1/gt/ftv-1.png      -O   tb1/gt/ftv-1.png
                    wget http://epg.51zmt.top:8000/tb1/gt/ftv-taiwan.png      -O   tb1/gt/ftv-taiwan.png
                    wget http://epg.51zmt.top:8000/tb1/gt/民视.png      -O   tb1/gt/民视.png
                    wget http://epg.51zmt.top:8000/tb1/gt/中视菁采.png      -O   tb1/gt/中视菁采.png
                    wget http://epg.51zmt.top:8000/tb1/gt/TVBS精采.png      -O   tb1/gt/TVBS精采.png
                    wget http://epg.51zmt.top:8000/tb1/gt/BabyFirst.png      -O   tb1/gt/BabyFirst.png
                    wget http://epg.51zmt.top:8000/tb1/gt/ftv-zongyi.png      -O   tb1/gt/ftv-zongyi.png
                    wget http://epg.51zmt.top:8000/tb1/gt/huayimbc.png      -O   tb1/gt/huayimbc.png
                    wget http://epg.51zmt.top:8000/tb1/gt/traceurban.png      -O   tb1/gt/traceurban.png
                    wget http://epg.51zmt.top:8000/tb1/gt/fashionone.png      -O   tb1/gt/fashionone.png
                    wget http://epg.51zmt.top:8000/tb1/gt/龙华日韩.png      -O   tb1/gt/龙华日韩.png
                    wget http://epg.51zmt.top:8000/tb1/gt/靖天戏剧.png      -O   tb1/gt/靖天戏剧.png
                    wget http://epg.51zmt.top:8000/tb1/gt/靖天电影.png      -O   tb1/gt/靖天电影.png
                    wget http://epg.51zmt.top:8000/tb1/gt/Wakuwaku.png      -O   tb1/gt/Wakuwaku.png
                    wget http://epg.51zmt.top:8000/tb1/gt/中视经典.png      -O   tb1/gt/中视经典.png
                    wget http://epg.51zmt.top:8000/tb1/gt/ifun1.png      -O   tb1/gt/ifun1.png
                    wget http://epg.51zmt.top:8000/tb1/gt/ifun2.png      -O   tb1/gt/ifun2.png
                    wget http://epg.51zmt.top:8000/tb1/gt/ifun3.png      -O   tb1/gt/ifun3.png
                    wget http://epg.51zmt.top:8000/tb1/gt/中视新闻.png      -O   tb1/gt/中视新闻.png
                    wget http://epg.51zmt.top:8000/tb1/gt/CrimeInvestigation.png      -O   tb1/gt/CrimeInvestigation.png
                    wget http://epg.51zmt.top:8000/tb1/gt/cnex.png      -O   tb1/gt/cnex.png
                    wget http://epg.51zmt.top:8000/tb1/gt/采昌影剧.png      -O   tb1/gt/采昌影剧.png
                    wget http://epg.51zmt.top:8000/tb1/gt/智林体育台.png      -O   tb1/gt/智林体育台.png
                    wget http://epg.51zmt.top:8000/tb1/gt/影迷纪实.png      -O   tb1/gt/影迷纪实.png
                    wget http://epg.51zmt.top:8000/tb1/gt/影迷电影.png      -O   tb1/gt/影迷电影.png
                    wget http://epg.51zmt.top:8000/tb1/gt/eltv.png      -O   tb1/gt/eltv.png
                    wget http://epg.51zmt.top:8000/tb1/gt/靖天国际.png      -O   tb1/gt/靖天国际.png
                    wget http://epg.51zmt.top:8000/tb1/gt/longhuadonghua.png      -O   tb1/gt/longhuadonghua.png
                    wget http://epg.51zmt.top:8000/tb1/gt/MTV.png      -O   tb1/gt/MTV.png
                    wget http://epg.51zmt.top:8000/tb1/gt/elta_sports2.png      -O   tb1/gt/elta_sports2.png
                    wget http://epg.51zmt.top:8000/tb1/gt/luxetv.png      -O   tb1/gt/luxetv.png
                    wget http://epg.51zmt.top:8000/tb1/gt/roller.png      -O   tb1/gt/roller.png
                    wget http://epg.51zmt.top:8000/tb1/gt/asiazonghe.png      -O   tb1/gt/asiazonghe.png
                    wget http://epg.51zmt.top:8000/tb1/gt/huanyuzonghe.png      -O   tb1/gt/huanyuzonghe.png
                    wget http://epg.51zmt.top:8000/tb1/gt/weilaojingcai.png      -O   tb1/gt/weilaojingcai.png
                    wget http://epg.51zmt.top:8000/tb1/gt/etoday.png      -O   tb1/gt/etoday.png
                    wget http://epg.51zmt.top:8000/tb1/gt/badayou.png      -O   tb1/gt/badayou.png
                    wget http://epg.51zmt.top:8000/tb1/gt/taiwanxiju.png      -O   tb1/gt/taiwanxiju.png
                    wget http://epg.51zmt.top:8000/tb1/gt/elta_yingju.png      -O   tb1/gt/elta_yingju.png
                    wget http://epg.51zmt.top:8000/tb1/gt/my101.png      -O   tb1/gt/my101.png
                    wget http://epg.51zmt.top:8000/tb1/gt/starmovieyule.png      -O   tb1/gt/starmovieyule.png
                    wget http://epg.51zmt.top:8000/tb1/gt/huanyucaijing.png      -O   tb1/gt/huanyucaijing.png
                    wget http://epg.51zmt.top:8000/tb1/gt/catchplay.png      -O   tb1/gt/catchplay.png
                    wget http://epg.51zmt.top:8000/tb1/gt/MyCinemaEurope.png      -O   tb1/gt/MyCinemaEurope.png
                    wget http://epg.51zmt.top:8000/tb1/gt/tfc.png      -O   tb1/gt/tfc.png
                    wget http://epg.51zmt.top:8000/tb1/gt/mykids.png      -O   tb1/gt/mykids.png
                    wget http://epg.51zmt.top:8000/tb1/gt/eata_sports1.png      -O   tb1/gt/eata_sports1.png
                    wget http://epg.51zmt.top:8000/tb1/gt/eata_sports3.png      -O   tb1/gt/eata_sports3.png
                    wget http://epg.51zmt.top:8000/tb1/gt/wolvesvalley.png      -O   tb1/gt/wolvesvalley.png
                    wget http://epg.51zmt.top:8000/tb1/gt/fooldplanet.png      -O   tb1/gt/fooldplanet.png
                    wget http://epg.51zmt.top:8000/tb1/gt/eyelvyou.png      -O   tb1/gt/eyelvyou.png
                    wget http://epg.51zmt.top:8000/tb1/gt/elta_zonghehd.png      -O   tb1/gt/elta_zonghehd.png
                    wget http://epg.51zmt.top:8000/tb1/gt/tiantian.png      -O   tb1/gt/tiantian.png
                    wget http://epg.51zmt.top:8000/tb1/gt/setxiju.png      -O   tb1/gt/setxiju.png
                    wget http://epg.51zmt.top:8000/tb1/gt/eyexiju.png      -O   tb1/gt/eyexiju.png
                    wget http://epg.51zmt.top:8000/tb1/gt/mandi_japan.png      -O   tb1/gt/mandi_japan.png
                    wget http://epg.51zmt.top:8000/tb1/gt/StarMoviesHD.png      -O   tb1/gt/StarMoviesHD.png
                    wget http://epg.51zmt.top:8000/tb1/gt/huayi_yingju.png      -O   tb1/gt/huayi_yingju.png
                    wget http://epg.51zmt.top:8000/tb1/gt/weixin.png      -O   tb1/gt/weixin.png
                    wget http://epg.51zmt.top:8000/tb1/gt/澳亚卫视.png      -O   tb1/gt/澳亚卫视.png
                    wget http://epg.51zmt.top:8000/tb1/gt/NHKWorld.png      -O   tb1/gt/NHKWorld.png
                    wget http://epg.51zmt.top:8000/tb1/gt/natgeowild.png      -O   tb1/gt/natgeowild.png
                    wget http://epg.51zmt.top:8000/tb1/gt/mezzo.png      -O   tb1/gt/mezzo.png
                    wget http://epg.51zmt.top:8000/tb1/gt/Lifetime.png      -O   tb1/gt/Lifetime.png
                    wget http://epg.51zmt.top:8000/tb1/gt/BBCWORLDNEWSASIA.png      -O   tb1/gt/BBCWORLDNEWSASIA.png
                    wget http://epg.51zmt.top:8000/tb1/gt/CNCartoon.png      -O   tb1/gt/CNCartoon.png
                    wget http://epg.51zmt.top:8000/tb1/gt/DisneyJunior.png      -O   tb1/gt/DisneyJunior.png
                    wget http://epg.51zmt.top:8000/tb1/gt/CNBC.png      -O   tb1/gt/CNBC.png
                    wget http://epg.51zmt.top:8000/tb1/gt/natgeo.png      -O   tb1/gt/natgeo.png
                    wget http://epg.51zmt.top:8000/tb1/gt/faguoshishang.png      -O   tb1/gt/faguoshishang.png
                    wget http://epg.51zmt.top:8000/tb1/gt/FXHD.png      -O   tb1/gt/FXHD.png
                    wget http://epg.51zmt.top:8000/tb1/gt/DW.png      -O   tb1/gt/DW.png
                    wget http://epg.51zmt.top:8000/tb1/gt/tv5monde.png      -O   tb1/gt/tv5monde.png
                    wget http://epg.51zmt.top:8000/tb1/gt/france24.png      -O   tb1/gt/france24.png
                    wget http://epg.51zmt.top:8000/tb1/gt/SkyNews.png      -O   tb1/gt/SkyNews.png
                    wget http://epg.51zmt.top:8000/tb1/gt/cinemaworld.png      -O   tb1/gt/cinemaworld.png
                    wget http://epg.51zmt.top:8000/tb1/CCTV/CGTNDoc.png      -O   tb1/CCTV/CGTNDoc.png
                    wget http://epg.51zmt.top:8000/tb1/gt/TRACESportStars.png      -O   tb1/gt/TRACESportStars.png
                    wget http://epg.51zmt.top:8000/tb1/gt/outdoor.png      -O   tb1/gt/outdoor.png
                    wget http://epg.51zmt.top:8000/tb1/gt/HITS.png      -O   tb1/gt/HITS.png
                    wget http://epg.51zmt.top:8000/tb1/gt/CNNNews.png      -O   tb1/gt/CNNNews.png
                    wget http://epg.51zmt.top:8000/tb1/gt/NationalGeographic_taiwan.png      -O   tb1/gt/NationalGeographic_taiwan.png
                    wget http://epg.51zmt.top:8000/tb1/gt/DiscoveryHD.png      -O   tb1/gt/DiscoveryHD.png
                    wget http://epg.51zmt.top:8000/tb1/gt/tlc.png      -O   tb1/gt/tlc.png
                    wget http://epg.51zmt.top:8000/tb1/gt/AnimalPlanet.png      -O   tb1/gt/AnimalPlanet.png
                    wget http://epg.51zmt.top:8000/tb1/gt/Disney.png      -O   tb1/gt/Disney.png
                    wget http://epg.51zmt.top:8000/tb1/gt/HBO.png      -O   tb1/gt/HBO.png
                    wget http://epg.51zmt.top:8000/tb1/gt/AXN.png      -O   tb1/gt/AXN.png
                    wget http://epg.51zmt.top:8000/tb1/gt/FOXMOVIES.png      -O   tb1/gt/FOXMOVIES.png
                    wget http://epg.51zmt.top:8000/tb1/gt/CinemaxHD.png      -O   tb1/gt/CinemaxHD.png
                    wget http://epg.51zmt.top:8000/tb1/gt/FOXSports.png      -O   tb1/gt/FOXSports.png
                    wget http://epg.51zmt.top:8000/tb1/gt/ELEVENsports1.png      -O   tb1/gt/ELEVENsports1.png
                    wget http://epg.51zmt.top:8000/tb1/gt/FOXHD.png      -O   tb1/gt/FOXHD.png
                    wget http://epg.51zmt.top:8000/tb1/gt/NHK.png      -O   tb1/gt/NHK.png
                    wget http://epg.51zmt.top:8000/tb1/gt/channelnewsasia.png      -O   tb1/gt/channelnewsasia.png
                    wget http://epg.51zmt.top:8000/tb1/gt/BloombergTV.png      -O   tb1/gt/BloombergTV.png
                    wget http://epg.51zmt.top:8000/tb1/gt/ArirangTV.png      -O   tb1/gt/ArirangTV.png
                    wget http://epg.51zmt.top:8000/tb1/gt/BBCLifestyle.png      -O   tb1/gt/BBCLifestyle.png
                    wget http://epg.51zmt.top:8000/tb1/gt/dreamworks.png      -O   tb1/gt/dreamworks.png
                    wget http://epg.51zmt.top:8000/tb1/gt/WarnerTV.png      -O   tb1/gt/WarnerTV.png
                    wget http://epg.51zmt.top:8000/tb1/gt/HBOHD.png      -O   tb1/gt/HBOHD.png
                    wget http://epg.51zmt.top:8000/tb1/gt/HBOHits.png      -O   tb1/gt/HBOHits.png
                    wget http://epg.51zmt.top:8000/tb1/gt/HBOSignature.png      -O   tb1/gt/HBOSignature.png
                    wget http://epg.51zmt.top:8000/tb1/gt/HBOFamily.png      -O   tb1/gt/HBOFamily.png
                    wget http://epg.51zmt.top:8000/tb1/gt/BlueAntEntertainment.png      -O   tb1/gt/BlueAntEntertainment.png
                    wget http://epg.51zmt.top:8000/tb1/gt/tvN.png      -O   tb1/gt/tvN.png
                    wget http://epg.51zmt.top:8000/tb1/gt/KMTV.png      -O   tb1/gt/KMTV.png
                    wget http://epg.51zmt.top:8000/tb1/gt/EVE.png      -O   tb1/gt/EVE.png
                    wget http://epg.51zmt.top:8000/tb1/gt/Discovery科学.png      -O   tb1/gt/Discovery科学.png
                    wget http://epg.51zmt.top:8000/tb1/gt/Discovery-Asia.png      -O   tb1/gt/Discovery-Asia.png
                    wget http://epg.51zmt.top:8000/tb1/gt/DMAX.png      -O   tb1/gt/DMAX.png
                    wget http://epg.51zmt.top:8000/tb1/gt/medici-arts.png      -O   tb1/gt/medici-arts.png
                    wget http://epg.51zmt.top:8000/tb1/gt/BLUEAntExtreme.png      -O   tb1/gt/BLUEAntExtreme.png
                    wget http://epg.51zmt.top:8000/tb1/gt/euronews.png      -O   tb1/gt/euronews.png
                    wget http://epg.51zmt.top:8000/tb1/gt/Nickelodeon.png      -O   tb1/gt/Nickelodeon.png
                    wget http://epg.51zmt.top:8000/tb1/gt/NickJr.png      -O   tb1/gt/NickJr.png
                    wget http://epg.51zmt.top:8000/tb1/gt/CBeebies.png      -O   tb1/gt/CBeebies.png
                    wget http://epg.51zmt.top:8000/tb1/gt/BOOMERANG.png      -O   tb1/gt/BOOMERANG.png
                    wget http://epg.51zmt.top:8000/tb1/gt/BBCEarth.png      -O   tb1/gt/BBCEarth.png
                    wget http://epg.51zmt.top:8000/tb1/gt/abcaus.png      -O   tb1/gt/abcaus.png
                    wget http://epg.51zmt.top:8000/tb1/gt/CNN.png      -O   tb1/gt/CNN.png
                    wget http://epg.51zmt.top:8000/tb1/gt/nhkworldp.png      -O   tb1/gt/nhkworldp.png
                    wget http://epg.51zmt.top:8000/tb1/gt/ELTA_Ent.png      -O   tb1/gt/ELTA_Ent.png
                    wget http://epg.51zmt.top:8000/tb1/gt/elevensports2.png      -O   tb1/gt/elevensports2.png
                    wget http://epg.51zmt.top:8000/tb1/gt/HistoryChannel.png      -O   tb1/gt/HistoryChannel.png
                    wget http://epg.51zmt.top:8000/tb1/gt/Smart知识台.png      -O   tb1/gt/Smart知识台.png
                    wget http://epg.51zmt.top:8000/tb1/gt/AMC.png      -O   tb1/gt/AMC.png
                    wget http://epg.51zmt.top:8000/tb1/gt/aljazeera.png      -O   tb1/gt/aljazeera.png
                    wget http://epg.51zmt.top:8000/tb1/gt/eurosport.png      -O   tb1/gt/eurosport.png
                    wget http://epg.51zmt.top:8000/tb1/gt/ANIMAX.png      -O   tb1/gt/ANIMAX.png
