#+TITLE: 最近这几天
#+DATE: 2015-12-09
#+SETUPFILE: ~/org/setupfile.org
#+JEKYLL_LAYOUT: post
#+JEKYLL_CATEGORIES: 
#+JEKYLL_TAGS: 
#+JEKYLL_PUBLISHED: false

* 郁结 
最近这几天，心中觉得郁结难解。想买一套房子，可惜囊中羞涩，选来选去都要还上几十年的贷款。仅仅是囊中羞涩也就罢了，连任性地回郑州看上两天房子的时间都没有。 
更何况买房子要这证明,那证明，少不了到处衙门跑，想到就是心烦。老母亲大人，身体每况愈下，连日失眠以致类月。姐姐帮着找了几地医生看， 也没有什么效果，真恨不得
当初学了医。

* 优化
{{{more}}}
去年十一月到现在公司，已经整整在这个游戏上花费了一年多的时间，回想起来，这一年都做了些什么，真是惭愧。幸好最近把精力都放在游戏优化和工作流程优化上。
虽然游戏的优化各种指标还没有达到我理想的境地，但工作流程优化显得更加困难一些。身边的同事，有些感觉整体浑浑噩噩，有些做事没有担当，推诿，转眼即忘，着实
令人头疼。游戏的优化，显得要更简单些，优化内存占用，缓存对象，优化逻辑。优化时，最好是有一个 Profile 作为依据，C++层面都是引擎，也没有能力去修改太多，
Lua 层面，我十分想做到一个和当年做 php 时用的一个 Profile，一个函数被调用了多少次， 一个函数在一段时间内最长执行时间。

* Lua C API
用 Lua，但对 Lua 内的很多机制其实并不了解，这次正好深入了解下。今天，用 Lua C API 实现了 lua 调用 C 函数， 也算是一大收获。但在看的过程中也能看出自己
C/C++ 基础薄弱, 还需要针对性地继续加强 C/C++学习，多写多看. 上面提到的 Profile，看了部分 LuaProfiler，luatrace 的代码，还没有完全跑起来。 接下来实现一个
很好的 Profiler 来当作 Lua 学习的阶段性成果.

* 方向
接下来要聚焦这些方向，看起来还是满满堂堂的。兴趣太多是我的一大缺点，这已经是收敛过后的列表了。
- 3D 游戏
- OpenGL
- Unreal
- 数学
- Cocos2d-x 2D 部分
- Lua
- C++
- Spacemacs

* 阅读
最近买了几本书:
- 编程之法
- 游戏设计的 263 个技巧
要扩大阅读量了。

* 新年 2016
转眼就要到新的一年了, 希望 2016 年成为努力的一年，成长的一年，收获的一年。加油！
